### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by mikroskeem** [TyphoonMC/TyphoonLimbo#23]
```
panic: runtime error: makeslice: len out of range
goroutine 7 [running]:
main.(*Player).ReadByteArray(0xc0000a82a0, 0xfffffffffffffff5, 0xc000112050, 0xb, 0xc, 0x0, 0x0)
     /home/mark/projects/TyphoonLimbo/utils.go:245 +0x40
main.(*PacketPlayPluginMessage).Read(0xc0000ea450, 0xc0000a82a0, 0x1, 0x5afa80, 0xc0000ea450)
     /home/mark/projects/TyphoonLimbo/packet_handle.go:414 +0x123
main.(*Player).HandlePacket(0xc0000a82a0, 0x9, 0x1, 0xc0000b2328, 0xc0000ea301, 0x0, 0x0)
     /home/mark/projects/TyphoonLimbo/packet_registry.go:62 +0x344
main.(*Player).ReadPacketWithoutCompression(0xc0000a82a0, 0x5afa80, 0xc0000ea390, 0x0, 0x0)
     /home/mark/projects/TyphoonLimbo/connection.go:195 +0xb5
main.(*Player).ReadPacket(0xc0000a82a0, 0x5afa80, 0xc0000ea390, 0x0, 0x0)
     /home/mark/projects/TyphoonLimbo/connection.go:175 +0x75
main.HandleConnection(0x5b0200, 0xc00000e0c8, 0x2)
     /home/mark/projects/TyphoonLimbo/limbo.go:84 +0x336
created by main.main
     /home/mark/projects/TyphoonLimbo/limbo.go:32 +0x1fd
```

Player who managed to cause this crash (accidentally) was using 1.8.8 and TyphoonLimbo is running behind Waterfall, if that helps.

**Comment by phase** [comment]
I spent some time looking at the code and here's what I could tell:

The Serverbound Plugin Message Packet has one of two formats:
```
1.7:
ChannelName: String
MessageLength: Short
Message: Byte[]
```
```
1.8-1.13:
ChannelName: String
Message: Byte[]
```
The issue is occurring with 1.8 clients and the error has to do with allocating a byte array that is too large, so I assume it has something to do with the length that is being read. This brings us to this:

https://github.com/TyphoonMC/TyphoonLimbo/blob/377fd7fab400da1b343b3d911a9f164b2fd740c0/packet_handle.go#L396-L398

1.7 clients don't use the `read` variable here because it has the length built into the packet, so `read` is probably returning the wrong result.

In `Player#ReadNStringLimited`, we can see that the length returned is whatever the VarInt size is read as and then converted to a u64

https://github.com/TyphoonMC/TyphoonLimbo/blob/a090f70fb6c10ec227c21958f23f18ab153a31b3/utils.go#L218-L223

@mikroskeem told me that this issue is _"pretty impossible to reproduce_", meaning there is something here that is inconsistent. My bet is on `binary.PutUvarint`. The [docs](https://golang.org/pkg/encoding/binary/#PutUvarint) say:

> The varint functions encode and decode single integer values using a variable-length encoding; smaller values require fewer bytes. For a specification, see https://developers.google.com/protocol-buffers/docs/encoding. 

Which means they're using the Google Buffer encoding. Minecraft uses a _slightly_ different encoding. The [Wiki.vg page on Data Types](https://wiki.vg/Data_types) says:

> Note that Minecraft's VarInts are not encoded using Protocol Buffers; it's just similar. If you try to use Protocol Buffers Varints with Minecraft's VarInts, you'll get incorrect results in some cases.

My suggestion is to strip out anywhere that uses the `binary` package for dealing with VarInts and write a new implementation of it.

**Comment by skyforce77** [comment]
Something to consider, thanks

**Comment by skyforce77** [comment]
[Please let me know if it fixes your issue](https://github.com/TyphoonMC/TyphoonLimbo/tree/varint)

**Comment by mikroskeem** [comment]
I'll drop it in prod and let you know

**Comment by skyforce77** [comment]
Thx

**Comment by mikroskeem** [comment]
```
panic: runtime error: makeslice: len out of range
goroutine 7 [running]:
main.(*Player).ReadByteArray(0xc0000a8230, 0xfffffffffffffff5, 0xc000016630, 0xb, 0xc, 0x0, 0x0)
     /home/mark/projects/TyphoonLimbo/utils.go:266 +0x40
main.(*PacketPlayPluginMessage).Read(0xc000070f00, 0xc0000a8230, 0x1, 0x5af980, 0xc000070f00)
     /home/mark/projects/TyphoonLimbo/packet_handle.go:414 +0x123
main.(*Player).HandlePacket(0xc0000a8230, 0x9, 0x1, 0xc0000b23b8, 0xc000070e01, 0x0, 0x0)
     /home/mark/projects/TyphoonLimbo/packet_registry.go:62 +0x344
main.(*Player).ReadPacketWithoutCompression(0xc0000a8230, 0x5af980, 0xc000070e40, 0x0, 0x0)
     /home/mark/projects/TyphoonLimbo/connection.go:195 +0xb5
main.(*Player).ReadPacket(0xc0000a8230, 0x5af980, 0xc000070e40, 0x0, 0x0)
     /home/mark/projects/TyphoonLimbo/connection.go:175 +0x75
main.HandleConnection(0x5b0100, 0xc00000e0c0, 0x2)
     /home/mark/projects/TyphoonLimbo/limbo.go:84 +0x336
created by main.main
     /home/mark/projects/TyphoonLimbo/limbo.go:32 +0x1fd
```

:confused:

**Comment by wasder** [comment]
Same here
```2019/03/14 10:44:38 193.70.80.21:36325(#325) connected.
2019/03/14 10:44:38 #325 -> 0 &{335 rncr.ru176.97.36.122ae8794578ee743e39bef72ddef3c7572 25565 2}
2019/03/14 10:44:38 #325 -> 0 &{Rubich}
2019/03/14 10:44:38 #325 <- 2 &{d979912c-bb24-4f23-a6ac-c32985a1e5d3 Rubich}
2019/03/14 10:44:38 #325 <- 35 &{0 3 1 2 255 default false}
2019/03/14 10:44:38 #325 <- 46 &{0 0 0 0 0 0 0}
2019/03/14 10:44:38 #325 <- 15 &{{"text":"","color":"dark_red"} 0}
2019/03/14 10:44:38 #325 <- 12 &{[207 103 92 25 145 204 75 204 132 80 176 109 232 33 64 252] 0 [{"text":"Лобби авторизации ","bold":false,"color":"yellow"},{"text":"Ran","bold":true,"color":"dark_green"},{"text":"dom","bold":true,"color":"blue"},{"text":"Cra","bold":true,"color":"dark_red"},{"text":"ft","bold":true,"color":"gold"}] 1 2 0 0}
2019/03/14 10:44:38 #325 <- 73 &{0xc420010480 <nil>}
2019/03/14 10:44:38 #325 -> 9 &{REGISTER [108 112 117 99 0 70 77 76 0 70 77 76 124 72 83 0 70 79 82 71 69 0 87 68 76 124 73 78 73 84 0 66 117 110 103 101 101 67 111 114 100 87]}
panic: runtime error: makeslice: len out of range

goroutine 359 [running]:
main.(*Player).ReadByteArray(0xc420450000, 0xffffffffffffffc7, 0xc4202120f0, 0x42, 0x43, 0x0, 0x0)
        /home/mc/test/login/TyphoonLimbo/utils.go:245 +0x40
main.(*PacketPlayPluginMessage).Read(0xc4200b6630, 0xc420450000, 0xa, 0x649460, 0xc4200b6630)
        /home/mc/test/login/TyphoonLimbo/packet_handle.go:413 +0x141
main.(*Player).HandlePacket(0xc420450000, 0x9, 0xa, 0xc42001d7e8, 0x1, 0x0, 0x0)
        /home/mc/test/login/TyphoonLimbo/packet_registry.go:62 +0x36c
main.(*Player).ReadPacketWithoutCompression(0xc420450000, 0x649460, 0xc4200b6540, 0x0, 0x0)
        /home/mc/test/login/TyphoonLimbo/connection.go:195 +0xb8
main.(*Player).ReadPacket(0xc420450000, 0x649460, 0xc4200b6540, 0x0, 0x0)
        /home/mc/test/login/TyphoonLimbo/connection.go:175 +0x72
main.HandleConnection(0x64a240, 0xc42044c000, 0x145)
        /home/mc/test/login/TyphoonLimbo/limbo.go:84 +0x393
created by main.main
        /home/mc/test/login/TyphoonLimbo/limbo.go:32 +0x232
```

**Comment by skyforce77** [comment]
@mikroskeem Was your crash also related to the "REGISTER" custom packet ?

**Comment by mikroskeem** [comment]
It's about a month since the time I reported this again so I cannot remember that sadly, but lately I've been able to reproduce this using brand channel 😄

**Comment by wasder** [comment]
Here is another one:
```
2019/03/15 23:19:51 #55 -> 0 &{Korobochka}
2019/03/15 23:19:51 #55 <- 2 &{d979912c-bb24-4f23-a6ac-c32985a1e5d3 Korobochka}
2019/03/15 23:19:51 #55 <- 37 &{0 3 1 2 255 default false}
2019/03/15 23:19:51 #55 <- 50 &{0 0 0 0 0 0 0}
2019/03/15 23:19:51 #55 <- 14 &{{"text":"","color":"dark_red"} 0}
2019/03/15 23:19:51 #55 <- 12 &{[36 113 4 35 199 247 74 250 162 73 158 27 131 17 137 53] 0 [{"text":"Лобби авторизации ","bold":false,"color":"yellow"},{"text":"Ran","bold":true,"color":"dark_green"},{"text":"dom","bold":true,"color":"blue"},{"text":"Cra","bold":true,"color":"dark_red"},{"text":"ft","bold":true,"color":"gold"}] 1 2 0 0}
2019/03/15 23:19:51 #55 <- 78 &{0xc420010480 <nil>}
2019/03/15 23:19:51 #55 -> 9 &{minecraft:register [108 101 103 97 99 121 58 108 112 117 99 0 108 101 103 97 99 121 58 102 109 108 0 108 101 103 97 99 121 58 102 109 108 124 104 115 0 108 101 103 97 99 121 58 102 111 114 103 101 0 108 101 103 97 99 121 58 119 100 108 124 105 110 105 116 0 98 117 110 103 101 101 99 111 114 100 58 109 97 105 110 0]}
2019/03/15 23:19:51 #55 -> 9 &{bungeecord:main [0 22 67 77 73 80 108 97 121 101 114 67 104 97 110 103 101 67 104 97 110 110 101 108 0 120 0 8 75 105 110 103 100 111 109 115 0 108 118 97 108 101 114 97 49 51 51 55 55 44 78 105 107 105 116 97 83 121 104 44 65 108 101 120 111 90 44 75 105 108 121 97 110 100 114 97 44 76 117 120 117 114 105 111 117 115 110 101 115 115 44 77 114 66 97 108 108 107 44 84 97 122 95 78 97 95 86 97 108 97 104 44 77 111 114 111 122 95 78 44 110 97 105 108 97 121 117 112 111 118 49 55 44 84 104 101 72 97 112 112 121 78 105 103 97 95 163]}
panic: runtime error: makeslice: len out of range

goroutine 62 [running]:
main.(*Player).ReadByteArray(0xc4200e2c40, 0xfffffffffffffff1, 0xc4201b90d0, 0xf, 0x10, 0x0, 0x0)
        /home/mc/test/login/TyphoonLimbo/utils.go:245 +0x40
main.(*PacketPlayPluginMessage).Read(0xc4201e7a70, 0xc4200e2c40, 0x1, 0x649460, 0xc4201e7a70)
        /home/mc/test/login/TyphoonLimbo/packet_handle.go:413 +0x141
main.(*Player).HandlePacket(0xc4200e2c40, 0x9, 0x1, 0xc4200a0730, 0x1, 0x0, 0x0)
        /home/mc/test/login/TyphoonLimbo/packet_registry.go:62 +0x36c
main.(*Player).ReadPacketWithoutCompression(0xc4200e2c40, 0x649460, 0xc4201e7980, 0x0, 0x0)
        /home/mc/test/login/TyphoonLimbo/connection.go:195 +0xb8
main.(*Player).ReadPacket(0xc4200e2c40, 0x649460, 0xc4201e7980, 0x0, 0x0)
        /home/mc/test/login/TyphoonLimbo/connection.go:175 +0x72
main.HandleConnection(0x64a240, 0xc4200cc0e0, 0x37)
        /home/mc/test/login/TyphoonLimbo/limbo.go:84 +0x393
created by main.main
        /home/mc/test/login/TyphoonLimbo/limbo.go:32 +0x232

```

**Comment by skyforce77** [comment]
Seems like TyphoonLimbo doesn't like plugin messages so much.
I'll try to mock up plugin messages and see.

Next time you see this issue, could you please include all the player informations, starting by this packet :
`2019/03/14 10:44:38 #325 -> 0 &{335 rncr.ru176.97.36.122ae8794578ee743e39bef72ddef3c7572 25565 2}`
It has the protocol version and will help to find more about this issue

**Comment by mikroskeem** [comment]
Can't you just ignore them? They aren't mandatory for keeping up the connections if I recall correctly.

---- On Sat, 16 Mar 2019 10:33:06 +0000 notifications@github.com wrote ----

Seems like TyphoonLimbo doesn't like plugin messages so much
